repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: double-quote-string-fixer
    - id: requirements-txt-fixer
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.21.0
  hooks:
    - id: check-metaschema
      name: Validate Tool and Blackbox Schema
      files: ^schemas/.*\.schema\.json$
      stages: [push]
    - id: check-jsonschema
      name: Validate Tool
      args: ["--schemafile", "schemas/tool.schema.json"]
      files: ^tools/.*\.tool\.(yml|yaml)$
      stages: [push]
    - id: check-jsonschema
      name: Validate Blackbox
      args: ["--schemafile", "schemas/blackbox.schema.json"]
      files: ^blackboxes/.*\.blackbox\.(yml|yaml)$
      stages: [push]
