# This is a basic workflow to verify yaml data for tools and blackboxes

name: Validate YAML data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  test-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: TEST Tools
        uses: thiagodnf/yaml-schema-checker@v0.0.8
        with:
          jsonSchemaFile: schemas/tool.schema.json
          yamlFiles: |
            test/tools/*.yml
      - name: TEST Blackboxes
        uses: thiagodnf/yaml-schema-checker@v0.0.8
        with:
          jsonSchemaFile: schemas/blackbox.schema.json
          yamlFiles: |
            test/blackboxes/*.yml
