# This is a basic validation workflow for TESTING yaml data for tools and blackboxes

name: Last check of YAML test data

on:
  push:
    branches: [ "main" ]
    paths:
     - 'test/**/*.yml'

jobs:
  clean-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show empty folders
        run: |
          ls -l ${GITHUB_WORKSPACE}/test/tools
          ls -l ${GITHUB_WORKSPACE}/test/blackboxes
