# This is a basic validation workflow for TESTING yaml data for tools and blackboxes

name: Last check of YAML test data

on:
  push:
    branches: [ "main" ]
    paths:
     - 'test/**/*.yml'

jobs:
  clean-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean test folder from old data
        id: clean
        run: |
          rm -rf ${GITHUB_WORKSPACE}/test/tools/*
          rm -rf ${GITHUB_WORKSPACE}/test/blackboxes/*
          echo "Removed old data from test folder"
