# This is a basic validation workflow for TESTING yaml data for tools and blackboxes

name: Last check of YAML test data

on:
  push:
    branches: [ "main" ]
    paths:
     - 'test/**/*.yml'

jobs:
  clean-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean test folder from old data
        id: clean
        run: |
          rm -f test/tools/*
          rm -f test/blackboxes/*
          echo "Removed old data from test folder"
      - name: Commit files and push it
        run: |
          git config --global user.email "furesh@host.com"
          git config --global user.name "github actions"
          git add .
          git commit -m "furesh: clean repo"
          git push --force
